name: build
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conda Environment Activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: MIVP
          environment-file: environment.yml

      - name: Videos Generation
        run: python main.py

      - name: Screenshots
        run: ./screenshot

      - name: Deployment Setup
        run: rm .gitignore

      - name: Deployment
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
          PRESERVE: true
